baseURL = 'http://jlh18.github.io/'
languageCode = 'en-us'
title = 'Joseph Hua'
theme = 'PaperMod'

[Params]
  subtitle = "Joseph Hua"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module.mounts]
source = 'images'
target = 'static/images'